___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright by Pierian Data Inc.</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# MAIN

## Imports

In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [76]:
df = pd.read_csv('Advertising.csv')

X = df.drop('sales', axis=1)
y = df['sales']

In [77]:
from sklearn.preprocessing import PolynomialFeatures

In [78]:
polynomial_converter = PolynomialFeatures(degree=3, include_bias=False)
poly_features        = polynomial_converter.fit_transform(X=X)

In [79]:
print(X.shape, '\n')
print(poly_features.shape)

(200, 3) 

(200, 19)


In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(140, 19)
(60, 19)
(140,)
(60,)


In [82]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test  = scaler.transform(X_test)

In [83]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [84]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [85]:
from sklearn.linear_model import Ridge

In [86]:
ridge_model = Ridge(alpha=10)
ridge_model.fit(X_train, y_train)

Ridge(alpha=10)

In [87]:
test_predictions = ridge_model.predict(X_test)

In [88]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

MAE  = mean_absolute_error(y_true=y_test, y_pred=test_predictions)
MSE  = mean_squared_error (y_true=y_test, y_pred=test_predictions)
RMSE = np.sqrt(MSE)

print(MAE)
print(MSE)
print(RMSE)

0.5774404204714166
0.8003783071528348
0.8946386461319648


In [92]:
from sklearn.linear_model import RidgeCV

ridge_CV_model = RidgeCV(alphas=(0.1, 1.0, 10.0), scoring='neg_mean_absolute_error')
ridge_CV_model.fit(X_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [93]:
ridge_CV_model.alpha_

0.1

In [91]:
from sklearn.metrics import SCORERS

SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_wei

In [94]:
test_predictions = ridge_CV_model.predict(X_test)

MAE  = mean_absolute_error(y_true=y_test, y_pred=test_predictions)
MSE  = mean_squared_error (y_true=y_test, y_pred=test_predictions)
RMSE = np.sqrt(MSE)

print(MAE)
print(MSE)
print(RMSE)

0.4273774884350411
0.38201298815370915
0.6180719926947905


In [95]:
ridge_CV_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [96]:
ridge_CV_model.best_score_

-0.3749223340292958

In [99]:
from sklearn.linear_model import LassoCV

lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5)
lasso_cv_model.fit(X=X_train, y=y_train)
lasso_cv_model.alpha_

0.4943070909225832

In [100]:
test_predictions = lasso_cv_model.predict(X=X_test)

MAE  = mean_absolute_error(y_true=y_test, y_pred=test_predictions)
MSE  = mean_squared_error (y_true=y_test, y_pred=test_predictions)
RMSE = np.sqrt(MSE)

print(MAE)
print(MSE)
print(RMSE)

0.6541723161252864
1.2787088713079873
1.1308001022762544


In [101]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [102]:
from sklearn.linear_model import ElasticNetCV

elastic_model = ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0],
                            eps=0.001, n_alphas=100, max_iter=1000000)

elastic_model.fit(X=X_train, y=y_train)

elastic_model.l1_ratio

[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1.0]

In [103]:
elastic_model.l1_ratio_

1.0

In [105]:
elastic_model.alpha_

0.004943070909225833

In [106]:
lasso_cv_model.alpha_

0.4943070909225832

In [107]:
test_predictions = elastic_model.predict(X=X_test)

MAE  = mean_absolute_error(y_true=y_test, y_pred=test_predictions)
MSE  = mean_squared_error (y_true=y_test, y_pred=test_predictions)
RMSE = np.sqrt(MSE)

print(MAE)
print(MSE)
print(RMSE)

0.43350346185900696
0.36761675741990707
0.6063140748984037


# Regularization with SciKit-Learn

Previously we created a new polynomial feature set and then applied our standard linear regression on it, but we can be smarter about model choice and utilize regularization.

Regularization attempts to minimize the RSS (residual sum of squares) *and* a penalty factor. This penalty factor will penalize models that have coefficients that are too large. Some methods of regularization will actually cause non useful features to have a coefficient of zero, in which case the model does not consider the feature.

Let's explore two methods of regularization, Ridge Regression and Lasso. We'll combine these with the polynomial feature set (it wouldn't be as effective to perform regularization of a model on such a small original feature set of the original X).

## Data and Setup

In [23]:
df = pd.read_csv("Advertising.csv")
X = df.drop('sales',axis=1)
y = df['sales']

### Polynomial Conversion

In [24]:
from sklearn.preprocessing import PolynomialFeatures

In [25]:
polynomial_converter = PolynomialFeatures(degree=3,include_bias=False)

In [26]:
poly_features = polynomial_converter.fit_transform(X)

### Train | Test Split

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

----
----

## Scaling the Data

While our particular data set has all the values in the same order of magnitude ($1000s of dollars spent), typically that won't be the case on a dataset, and since the mathematics behind regularized models will sum coefficients together, its important to standardize the features. Review the theory videos for more info, as well as a discussion on why we only **fit** to the training data, and **transform** on both sets separately.

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
# help(StandardScaler)

In [31]:
scaler = StandardScaler()

In [32]:
scaler.fit(X_train)

StandardScaler()

In [33]:
X_train = scaler.transform(X_train)

In [34]:
X_test = scaler.transform(X_test)

## Ridge Regression

Make sure to view video lectures for full explanation of Ridge Regression and choosing an alpha.

In [35]:
from sklearn.linear_model import Ridge

In [36]:
ridge_model = Ridge(alpha=10)

In [37]:
ridge_model.fit(X_train,y_train)

Ridge(alpha=10)

In [38]:
test_predictions = ridge_model.predict(X_test)

In [39]:
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [40]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [41]:
MAE

0.5774404204714166

In [42]:
RMSE

0.8946386461319648

How did it perform on the training set? (This will be used later on for comparison)

In [43]:
# Training Set Performance
train_predictions = ridge_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.5288348183025305

### Choosing an alpha value with Cross-Validation

Review the theory video for full details.

In [44]:
from sklearn.linear_model import RidgeCV

In [45]:
# help(RidgeCV)

In [46]:
# Choosing a scoring: https://scikit-learn.org/stable/modules/model_evaluation.html
# Negative RMSE so all metrics follow convention "Higher is better"

# See all options: sklearn.metrics.SCORERS.keys()
ridge_cv_model = RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')

In [47]:
# The more alpha options you pass, the longer this will take.
# Fortunately our data set is still pretty small
ridge_cv_model.fit(X_train,y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), scoring='neg_mean_absolute_error')

In [48]:
ridge_cv_model.alpha_

0.1

In [49]:
test_predictions = ridge_cv_model.predict(X_test)

In [50]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [51]:
MAE

0.4273774884350411

In [52]:
RMSE

0.6180719926947905

In [53]:
# Training Set Performance
# Training Set Performance
train_predictions = ridge_cv_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.3094132105655636

In [54]:
ridge_cv_model.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])


-----

## Lasso Regression

In [55]:
from sklearn.linear_model import LassoCV

In [56]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html
lasso_cv_model = LassoCV(eps=0.1,n_alphas=100,cv=5)

In [57]:
lasso_cv_model.fit(X_train,y_train)

LassoCV(cv=5, eps=0.1)

In [58]:
lasso_cv_model.alpha_

0.4943070909225832

In [59]:
test_predictions = lasso_cv_model.predict(X_test)

In [60]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [61]:
MAE

0.6541723161252864

In [62]:
RMSE

1.1308001022762544

In [63]:
# Training Set Performance
# Training Set Performance
train_predictions = lasso_cv_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.6912807140820701

In [64]:
lasso_cv_model.coef_

array([1.002651  , 0.        , 0.        , 0.        , 3.79745279,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

## Elastic Net

Elastic Net combines the penalties of ridge regression and lasso in an attempt to get the best of both worlds!

In [65]:
from sklearn.linear_model import ElasticNetCV

In [66]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],tol=0.01)

In [67]:
elastic_model.fit(X_train,y_train)

ElasticNetCV(l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1], tol=0.01)

In [68]:
elastic_model.l1_ratio_

1.0

In [69]:
test_predictions = elastic_model.predict(X_test)

In [70]:
MAE = mean_absolute_error(y_test,test_predictions)
MSE = mean_squared_error(y_test,test_predictions)
RMSE = np.sqrt(MSE)

In [71]:
MAE

0.5663262117569448

In [72]:
RMSE

0.7485546215633722

In [73]:
# Training Set Performance
# Training Set Performance
train_predictions = elastic_model.predict(X_train)
MAE = mean_absolute_error(y_train,train_predictions)
MAE

0.4307582990472369

In [74]:
elastic_model.coef_

array([ 3.78993643,  0.89232919,  0.28765395, -1.01843566,  2.15516144,
       -0.3567547 , -0.271502  ,  0.09741081,  0.        , -1.05563151,
        0.2362506 ,  0.07980911,  1.26170778,  0.01464706,  0.00462336,
       -0.39986069,  0.        ,  0.        , -0.05343757])

-----
---