# Simple Linear Regression

# Importing the libraries

In [1]:
# Working with array
import numpy as np
# Plotting chart, graph
import matplotlib.pyplot as plt
# Import dataset. Create the matrix of features and the dependent variable vector.
# Preprocess dataset
import pandas as pd
# Process missing data
from sklearn.impute import SimpleImputer
# One hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
# Splitting
from sklearn.model_selection import train_test_split
# Feature Scaling
from sklearn.preprocessing import StandardScaler

# Importing the dataset
- Create Data Frame
- Create Matrix of features & Dependent variable vector
    - Matrix of features: Independent variable. The variables containing some informations with which you can predict what you want to predict. The columns with which you're going to predict the dependent variable.
    - Dependent variable vector: The last column of dataset.

In [3]:
# Create Data frame
data_set = pd.read_csv('Salary_Data.csv')

# Matrix of Features, all the columns of the dataset except the last one
# iloc: Locate indexes, take the indexes of the column we want to extract from the dataset, we can get all the rows
# Select all rows, take all the columns except the last one
# ':': Taking every in the range, this case all the rows
# ':-1': Take the indexes from 0 to -1 (Excluding the last index)
# `value`: Taking the values
X = data_set.iloc[:, :-1].values

# Dependent variable vector (The last column of the dataset)
# `-1`: Get the last column
y = data_set.iloc[:, -1].values

In [4]:
print(f'{X}')
print('-----------------------------------------------------------------')
print(f'{y}')

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]
-----------------------------------------------------------------
[ 39343.  46205.  37731.  43525.  39891.  56642.  60150.  54445.  64445.
  57189.  63218.  55794.  56957.  57081.  61111.  67938.  66029.  83088.
  81363.  93940.  91738.  98273. 101302. 113812. 109431. 105582. 116969.
 112635. 122391. 121872.]


# Splitting (random) the dataset into the Training set and Test set
- Training set: Train ML model on existing observations. -> More data than test set (80%) -> Give the model more chance to understand and learn the correlations in the dataset.
- Test set: Evaluate the performance of the model on new observations (future data).
- Four parts:
    - X_train, X_test: Matrix of features
    - y_train, y_test: Dependent variable
- Why? The ML model expecting all of 04 parts as input
    - Training: X_train, y_train -> fit method
    - Prediction|Inference: X_test, y_test -> predict method

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [7]:
print(X_train)
print('----------------------------------------------')
print(X_test)
print('----------------------------------------------')
print(y_train)
print('----------------------------------------------')
print(y_test)

[[ 9.5]
 [ 2. ]
 [ 8.7]
 [ 7.9]
 [ 8.2]
 [ 2.2]
 [ 1.5]
 [ 9. ]
 [ 3. ]
 [ 5.9]
 [ 4.1]
 [ 3.2]
 [ 9.6]
 [ 1.3]
 [ 5.1]
 [ 1.1]
 [ 4.9]
 [10.5]
 [10.3]
 [ 3.7]
 [ 3.2]
 [ 4. ]
 [ 4. ]
 [ 2.9]]
----------------------------------------------
[[5.3]
 [7.1]
 [3.9]
 [6. ]
 [4.5]
 [6.8]]
----------------------------------------------
[116969.  43525. 109431. 101302. 113812.  39891.  37731. 105582.  60150.
  81363.  57081.  54445. 112635.  46205.  66029.  39343.  67938. 121872.
 122391.  57189.  64445.  56957.  55794.  56642.]
----------------------------------------------
[83088. 98273. 63218. 93940. 61111. 91738.]


# Training the Simple Linear Regression model on the Training set

# Predicting the Test set results

# Visualising the Training set results

# Visualising the Test set results