# $\color{red}{\text{Simple Linear Regression}}$

# $\color{red}{\text{Importing the libraries}}$

In [1]:
# Working with array
import numpy as np
# Plotting chart, graph
import matplotlib.pyplot as plt
# Import dataset. Create the matrix of features and the dependent variable vector.
# Preprocess dataset
import pandas as pd
# Process missing data
from sklearn.impute import SimpleImputer
# One hot encoding
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
# Splitting
from sklearn.model_selection import train_test_split
# Feature Scaling
from sklearn.preprocessing import StandardScaler

# $\color{red}{\text{Importing the dataset}}$
- Create Data Frame
- Create Matrix of features & Dependent variable vector
    - Matrix of features: Independent variable. The variables containing some informations with which you can predict what you want to predict. The columns with which you're going to predict the dependent variable.
    - Dependent variable vector: The last column of dataset.

In [1]:
# Create Data frame
data_set = pd.read_csv('Salary_Data.csv')

# Matrix of Features, all the columns of the dataset except the last one
# iloc: Locate indexes, take the indexes of the column we want to extract from the dataset, we can get all the rows
# Select all rows, take all the columns except the last one
# ':': Taking every in the range, this case all the rows
# ':-1': Take the indexes from 0 to -1 (Excluding the last index)
# `value`: Taking the values
X = data_set.iloc[:, :-1].values

# Dependent variable vector (The last column of the dataset)
# `-1`: Get the last column
y = data_set.iloc[:, -1].values

NameError: name 'pd' is not defined

In [ ]:
print(f'{X}')
print('-----------------------------------------------------------------')
print(f'{y}')

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
-----------------------------------------------------------------
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# $\color{red}{\text{Splitting (random) the dataset into the Training set and Test set}}$
- Training set: Train ML model on existing observations. -> More data than test set (80%) -> Give the model more chance to understand and learn the correlations in the dataset.
- Test set: Evaluate the performance of the model on new observations (future data).
- Four parts:
    - X_train, X_test: Matrix of features
    - y_train, y_test: Dependent variable
- Why? The ML model expecting all of 04 parts as input
    - Training: X_train, y_train -> fit method
    - Prediction|Inference: X_test, y_test -> predict method

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [ ]:
print(X_train)
print('----------------------------------------------')
print(X_test)
print('----------------------------------------------')
print(y_train)
print('----------------------------------------------')
print(y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
----------------------------------------------
[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
----------------------------------------------
[0 1 0 0 1 1 0 1]
----------------------------------------------
[0 1]


# $\color{red}{\text{Training the Simple Linear Regression model on the Training set}}$

# $\color{red}{\text{Predicting the Test set results}}$

# $\color{red}{\text{Visualising the Training set results}}$

# $\color{red}{\text{Visualising the Test set results}}$